// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package server

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonAc2ea9d1DecodeGoArwosOrgLoopyInternalServer(in *jlexer.Lexer, out *KVModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "key":
			out.Key = string(in.String())
		case "value":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Value).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAc2ea9d1EncodeGoArwosOrgLoopyInternalServer(out *jwriter.Writer, in KVModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"key\":"
		out.RawString(prefix[1:])
		out.String(string(in.Key))
	}
	if len(in.Value) != 0 {
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.Raw((in.Value).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v KVModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAc2ea9d1EncodeGoArwosOrgLoopyInternalServer(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v KVModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAc2ea9d1EncodeGoArwosOrgLoopyInternalServer(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *KVModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAc2ea9d1DecodeGoArwosOrgLoopyInternalServer(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *KVModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAc2ea9d1DecodeGoArwosOrgLoopyInternalServer(l, v)
}
